required-players: 1
countdown-seconds: 60
waiting-spawn: 
   world: 'world'
   x: -412
   y: 4
   z: 177
   yaw: 60
   pitch: 60
spawn:
   world: 'world'
   x: -514
   y: 4
   z: 198.7
   pitch: 60
   yaw: 60
      


      